# Generated by Django 4.2.6 on 2023-11-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='time_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
