# Generated by Django 4.2.6 on 2023-11-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_profile_time_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='smoker',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
