# Generated by Django 4.2.6 on 2023-11-22 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0003_alter_profile_smoker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='alcohlic',
            new_name='alcoholic',
        ),
    ]
